#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Zac-Kyoti
"""Index the addresses an upstream repo's docs cite that reference/kb/ does not mention yet.

    python3 tools/refs/upstream_index.py --repo ~/Documents/octabam --rev origin/main \
        --docs docs/firmware docs/contributing --out reference/kb/octabam-index.md

For every ColdFire address (0x40xxxxxx-0x46xxxxxx, 0x8000xxxx, 0x100xxxxx) in the docs at REV
that no reference/kb/*.md file names, the output lists the doc, its section heading and the
cited line, trimmed. These are the upstream's claims, not ours: a fact is verified only once it
moves into memory-map.md / caves.md with a confidence marker. Re-run after each sync; the
output is generated, never hand-edited.
"""
import argparse, datetime, pathlib, re, subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
ADDR = re.compile(r"0x(4[0-6][0-9a-f]{6}|8000[0-9a-f]{4}|100[0-9a-f]{5})\b", re.I)


def git(repo, *args):
    return subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True, text=True).stdout


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--rev", default="origin/main")
    ap.add_argument("--docs", nargs="+", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--name", default=None)
    a = ap.parse_args()
    repo = pathlib.Path(a.repo).expanduser()
    rev = git(repo, "rev-parse", "--short=8", a.rev).strip()
    name = a.name or repo.name
    kb = " ".join(p.read_text().lower() for p in (ROOT / "reference/kb").glob("*.md")
                  if p.name != pathlib.Path(a.out).name)
    files = [f for f in git(repo, "ls-tree", "-r", "--name-only", a.rev, "--", *a.docs).split()
             if f.endswith(".md")]
    out, total = [], 0
    for f in sorted(files):
        heading, rows = "", []
        for n, line in enumerate(git(repo, "show", f"{a.rev}:{f}").splitlines(), 1):
            if line.startswith("#"):
                heading = line.lstrip("#").strip()
                continue
            new = sorted({"0x" + m.group(1).lower() for m in ADDR.finditer(line)})
            new = [x for x in new if x not in kb]
            if not new:
                continue
            text = re.sub(r"\s+", " ", line.strip().strip("|")).strip()
            if len(text) > 220:
                text = text[:217] + "..."
            rows.append((heading, n, new, text))
        if rows:
            total += sum(len(r[2]) for r in rows)
            out.append(f"\n## `{f}`\n")
            last = None
            for heading, n, new, text in rows:
                if heading != last:
                    out.append(f"\n*{heading}*\n")
                    last = heading
                out.append(f"- L{n} " + " ".join(f"`{x}`" for x in new) + f" — {text}")
    head = [f"# {name} address index (generated)",
            "",
            f"> Generated by `tools/refs/upstream_index.py` from `{name}` @ `{rev}` "
            f"({', '.join(a.docs)}) on {datetime.date.today().isoformat()}.",
            "> **Upstream claims, not verified by us.** Only addresses no other `reference/kb/*.md` names are listed;",
            "> verify against `out/raw/section_3_MAIN_OS.bin` before relying on one, then move it into",
            "> `memory-map.md` with a confidence marker. Do not edit by hand; re-run after the next sync.",
            "",
            f"{total} address citations in {len(out) and sum(1 for x in out if x.startswith(chr(10)+'## '))} documents."]
    pathlib.Path(a.out).write_text("\n".join(head + out) + "\n")
    print(f"{a.out}: {total} citations")


if __name__ == "__main__":
    main()
