; GENERATED by tools/repitch_dsp_octabam.py from tools/patch_repitch_dsp.asm -- do not edit.
; Constants resolved (TAGVAL $504a23); the comments below are the standalone
; kernel's and still name them. Tables: two octabam blocks (rpk_dsp_ptable.py):
;   ptable  (81 words): render half-table +0
;   ptable2 (384 words): RPSP half-rows +0, RPS9 half-rows +$80
; zqinit copies both blocks into Y; no pass reads them after it.
; SPDX-License-Identifier: MIT
; SPDX-FileCopyrightText: 2026 Zac-Kyoti
; ===========================================================================
; repitch-kyoti rev 17 -- DSP side: the "virtual sampler" behind RPS9 / RPSP.
; Model (the ground truth this must match): tools/repitch_engine_model.py.
; Scope: reference/handoffs/REPITCH_FIDELITY_SCOPE.md; rev 17 (RPSP = mid + side through
; the SP's channel 6 filter (5 until 2026-10-08), the DSP load audit's budget): NOTES Session 120 continued (10).
; Plumbing: NOTES Session 110; rev 12/13: Session 111; rev 14: Session 112.
; Assembled by tools/dsp_xasm.py (NOT plain dsp_asm: this uses XY+ALU moves,
; equ and dc, and every word is disassembled back and checked);
; tools/repitch_dsp_src.py prepends the constants -- the table DATA lives in X
; memory since rev 14 (SPRING REVERB's own X tables, rewritten by the builder).
;
; WHERE IT RUNS. Unchanged from rev 10: the stock voice engine (payload A
; P:0x3a1, B P:0x1a4) is detoured at its kernel prologue (A P:0x40b, B
; P:0x20e): `move x:(r5),n6 / move y:(r5)+,a` becomes `bsr zqrp`, and both
; moves run at this routine's tail. For RPCH nothing else happens and the stock
; kernel runs. For RPS9/RPSP this routine writes the pass's output samples
; itself and sets r7 = 0, so the stock `do r7` skips (the DSP56300 skips a DO
; whose count is 0 -- stock relies on that for its own empty passes, measured).
;
; STATE ON ENTRY (measured in ot_emu against the real firmware):
;   r5  = table: x:(r5+i) = ring word offset of output i's frame (even),
;         y:(r5+i) = its fraction (Q24, unsigned)
;   r7  = outputs in this pass (0..16; the two passes of a frame add up to 16)
;   r3  = output pointer (x, 2 words per output), r2 = ring base (128-aligned
;         64-frame stereo ring)
;   r0  = the record pointer (live -- untouched), m6 = $7f
;   l:$40 = the increment r: x:$40 integer part, y:$40 fraction; the mode is
;         in y:$40 bits 0-1 (tools/patch_repitch_kyoti.s, rate_hook)
;   x:$418 = this track's offset in the core's 4-track loop (0,$20,$40,$60)
;   x:$419 = this track's unpacked per-voice record (set before the voice
;         module): word +$1E bit 12 = a trig starts in this frame (the driver
;         clears it after the frame), bits 8-11 = its sample offset
;   x:$20a = this track's AMP stage state (X:$6000 + $300 x track); +8 = its
;         level at the end of the last frame, linear Q23 (the AMP stage runs
;         after the voice module)
; Every frame runs this hook twice (the voice module's `do #2`: LC = 2, then 1);
; on a trig frame the first pass is the old sound's tail, the second starts the
; new one. An EMPTY pass (the first, when nothing is split) has no increment:
; y:$40 = 0, so it takes the RPCH exit and never reaches the engines (measured).
;
; MEMORY (Y:$795..$FFF is free on stock on both cores -- octabam, measured on
; hardware; SIDECHAIN3 takes $7f0-$9ff on both cores -- true only since Session 115:
; before it, SIDECHAIN3's keybus was $a00-$bff on payload A and overwrote this):
;   Y:STBASE + x:$418   per-track RPSP slot ($20 words): the mid's residual
;                       ring (modulo-addressed, so it starts the slot), then the state
;   Y:TABTAG            table tag; != TAGVAL => copy the tables in (once/core)
;   Y:SPTAB, Y:R9TAB    the virtual-ADC tables, 32 phases each (8 / 16 taps),
;                       from their 16 stored half-rows in X (rows 16-31 mirror)
;   Y:BTAB              the render's step table: (T[k], T[k+1]-T[k]) pairs
;
; REGISTERS. Uses a, b, x0, x1, y0, y1, r1, r4, r6, r7, m1 and m7 (saved and
; restored), n1, n2, n4, n5, n6, n7; r5 is borrowed during an RPSP tick and
; restored. Leaves r0, r2, m6 alone; advances r3 by two words per output. m1
; is $7f from zqtok on: an XY dual move needs its X pointer in r0-r3, and the
; ring's own modulo register is m6. So every table walk uses r4/r5 (linear) --
; r1 and r6 (m6 = $7f) wrap at a 128-word boundary (rev 14's first cutoff table
; did, on payload A only); r6 only walks inside one RPSP slot.
; Hardware stack: at most bsr + two nested DOs below zqrp (as rev 11-13).
;
; LABELS: no label may be a prefix of another (dsp_asm's lookup). zq*.
; ===========================================================================

; ---- the RPSP slot (Y:STBASE + x:$418, $20 words): the mid's residual ring
; (RINGM1+1 words, modulo-addressed, residuals / 4), then:
; Three output builds (RPK_OUT; tools/repitch_dsp_src.py keeps the ";@ list" blocks
; that name it): ch6 (channel 6's fixed filter + the side average), raw (outputs
; 7/8: neither), ch12 (channels 1/2: the trig-opened 4-pole on the mid and side).

zqrp:
        clr     a
        move    y:>$40,a1
        and     #<3,a                   ; (Z from a1; a2 and a0 are clear)
        beq     zqstk                   ; RPCH: stock, untouched
        move    a1,n1                   ; n1 = mode
        move    y:>$a7f,a
        cmp     #>$504a23,a
        beq     zqtok
        bsr     zqinit                  ; first use on this core (or a new build)
zqtok:
        move    m1,n4                   ; restored at zqdone
; ---- a trig (rev 14). The engines read the ring BEHIND the OT's position, and
; at a trig the frames behind the new sound hold stale audio (the last voice's,
; unscaled -- its AMP silenced it later in the chain). Stock reads only floor(p)
; and floor(p)+1; RPS9/RPSP would replay 8-13 frames of it at the new trig's
; full AMP: the crack at every trig start (user, rev 13; measured in ot_emu).
; So at the pass that starts the new sound, the 16 frames before its first
; frame become silence, and RPSP's slot starts clean (tag cleared: zqsp).
        move    x:>$418,a
        move    a1,n6                   ; the track offset
        move    x:>$419,r4
        move    #$7f,m1                 ; (not for r4's reads: its m4 is linear --
        clr     a                       ; x:$419 + $1E can straddle a 128-word block)
        move    x:(r4+$1e),a1           ; this track's unpacked per-voice word +$1E
        and     #>$1000,a               ; a trig starts in this frame?
        beq     zqnh
        move    lc,b                    ; ... and this is the frame's second pass (the
        cmp     #<1,b                   ; voice module's `do #2`: LC 2, then 1), where
        bne     zqnh                    ; the new sound starts. (Not a count of visits:
                                        ; an empty first pass carries mode 0 and never
                                        ; reaches this code -- rev 14 missed every trig
                                        ; landing on a frame boundary that way.)
        move    x:(r5),a                ; the new sound's first frame (ring word offset)
        sub     #<32,a
        and     #>$7e,a
        move    r2,x0
        add     x0,a                    ; (r2 is 128-aligned: r1 stays in the ring,
        move    a1,r1                   ;  and m1 = $7f wraps it)
        clr     a
        rep     #<32
        move    a,x:(r1)+
        move    n6,b
        add     #>$a0a,b
        move    b1,r1
        nop
        move    a,y:(r1)                ; RPSP: a clean slot at zqsp
zqnh:
        move    #>$fff000,y1            ; the 12-bit mask (RPS9; RPSP reloads it)
        move    n1,a
        cmp     #<2,a
        beq     zqsp

; ============================================================ RPS9 (Akai)
; output i = 12-bit(virtual ADC at p_i - c - 1): a 16-tap polyphase kernel over
; ring frames k_i-2c-1 .. k_i, all delivered. (NOT k_i+1: at a zero fraction
; the OT does not deliver it -- the stock kernel weights it 0. Measured.)
        do      r7,zq9e
        move    l:(r5)+,ab              ; a1 = ring word offset of k_i, b1 = its fraction
        sub     #<$1e,a                ; first tap = k_i - 2c - 1 frames: may go below 0,
        move    a1,n1                   ; which m1's modulo 128 wraps (|n1| <= 128)
        move    r2,r1
        lsr     #19,b                   ; phase 0..31
        lsl     #4,b                    ; x 16 taps
        add     #>$c00,b
        move    (r1)+n1                 ; modulo 128 under m1
        move    b1,r7                   ; the phase's row (the loop count is in LC now)
        clr     a       x:(r1)+,x0      ; (r7 is not used until the next instruction's Y)
        clr     b       x:(r1)+,x1      y:(r7)+,y0
; taps 1..15, unrolled (rev 17): a DO here cost 5 cycles per output, 8% of RPS9
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     x1,y0,b x:(r1)+,x1      y:(r7)+,y0
        mac     y0,x0,a
        mac     x1,y0,b a,x0            ; limit L
        tfr     x0,a    b,x0            ; limit R
        and     y1,a                    ; 12 bits: floor to a 1/2048 step
        tfr     x0,b    a1,x:(r3)+
        and     y1,b
        move    b1,x:(r3)+
zq9e:
        bra     zqdone

; ============================================================ RPSP (SP-1200)
; Rev 17: the mid (L + R)/2 goes through the SP -- the virtual ADC (8 taps) at
; the SP's clock, 12 bits, the band-limited render to 44.1 kHz -- then the SP's
; channel 6 output filter; the side (L - R)/2 is read clean, as far behind the
; OT's position as the mid's path delays it, and L, R = mid +/- side. The SP's
; clock period is 1.69 output samples, so an output interval holds at most one
; tick. A tick at u stores a new step; the render spreads the step (new - old)
; over this and the next L-1 outputs with the band-limited step response (the
; residual ring); the mid = current step + its ring slot.
zqsp:
        move    r7,b                    ; an empty pass: nothing to render, and x:(r5)
        tst     b                       ; is not this track's -- the slot waits for a
        beq     zqdone                  ; real pass (on the unit an empty pass is mode 0)
        move    n6,a
        add     #>$a00,a
        move    a1,r4                   ; this track's slot
        move    #>$5a5a08,x1
        move    y:(r4+$a),b
        cmp     x1,b
        beq     zqsok
        clr     b                       ; stale, first use or a trig: clean ring + state
        move    r4,r1
        do      #$1d,zqsz
        move    b,y:(r1)+
zqsz:
        move    x1,y:(r4+$a)
        move    r4,y:(r4+$19)
        move    #>$7fffff,x0
        move    x0,y:(r4+$16)
        move    #>$3630a9,x0                ; the read shift starts at its mean
        move    x0,y:(r4+$1c)
        bra     zqsrs                   ; "previous output" = this pass's first
zqsok:
        move    x:(r5),a                ; resync "previous" if this pass does not
        move    y:(r4+$13),x0         ; continue it: ring positions advance
        sub     x0,a                    ; continuously while a sound plays, so a
        and     #>$7e,a                 ; jump of more than 2 frames (4 words) means
        move    a1,b                    ; the state is stale (the track has been in
        cmp     #<4,b                   ; another mode meanwhile)
        ble     zqsnj
zqsrs:
        move    x:(r5),b
        move    b1,y:(r4+$13)
        move    y:(r5),b
        move    b1,y:(r4+$14)
zqsnj:
; ---- this pass's constants. r = int(r) + frac(r) as the DSP holds it (x:$40 is
; read for bit 0 only -- on the unit it reads $c1 at 1.0x; the table builder
; masks it too, measured in ot_emu -- and y:$40 carries the mode tag in its low
; bits, as the twin's r does): RF = frac(r); RH = r / 2, unsigned Q23 (the tick's
; u x r); the side's offset behind the OT = c + 1 frames + MS_SIDE_DELAY
; increments + the smoothed read shift, its integer part doubled (ring words;
; the fraction stays one)
        move    y:>$40,b
        move    b1,y:(r4+$1b)
        clr     a
        move    x:>$40,a1
        and     #<1,a
        move    y:>$40,a0               ; a = r as 24.24
        asr     a                       ; a0 = RH = r x 2^23, unsigned (a1 = 0)
        move    a0,y:(r4+$1a)
        move    a0,y0
        move    #>$2e28f6,x0
        mpyuu   y0,x0,a                 ; (MS_SIDE_DELAY / 16) r x 2^47 (RH unsigned; < 2^47)
        asr     #19,a,a                 ; -> MS_SIDE_DELAY r, 24.24
        add     #<$4,a               ; + c + 1 frames
        move    y:(r4+$1c),b
        asr     #22,b,b                 ; + the read shift (Q22 -> 24.24)
        add     b,a
        move    a1,x0
        add     x0,a                    ; integer part x 2
        move    a1,y:(r4+$11)
        move    a0,y:(r4+$12)
        move    r2,y:(r4+$15)
        move    r7,n1                   ; the pass count (r7 becomes the ring pointer)
        move    m7,n7                   ; restored at zqoe
        move    #$9,m7
        move    y:(r4+$19),r7
        lua     (r4+$b),r6           ; r6 walks TAU .. SPV once per output (m6 = $7f:
        move    #>$fffff4,n6             ; the slot does not straddle 128 words)
        do      n1,zqoe
        move    y:(r6),a
        sub     #>$100000,a             ; tau, less this output interval
        move    a1,y:(r6)+              ; (no tick: the step holds)
        bge     zqout
; ---- a tick at u = tau (PSP > 1: at most one per output interval)
        add     #>$1b1855,a              ; tau += PSP
        move    a1,y:(r4+$b)
        sub     #>$b1855,a
        asl     #3,a,a
        move    a1,x1                   ; u, Q23 (x1 is free until the render)
        move    y:(r4+$18),a          ; phi = frac(phi + r)
        move    y:(r4+$1b),y0
        add     y0,a
        move    a1,y:(r4+$18)
        lsr     a                       ; Q24 phi >> 1 = the same phi as Q23
        move    a1,y0
        mpyi    #$6c6152,y0,b              ; (PSP/2)*phi = PSP*phi * 2^46: the read shift
        move    y:(r4+$1c),y1          ; (b1 = the shift, Q22) into its one-pole mean
        move    b1,a
        sub     y1,a
        asr     #$4,a,a
        add     y1,a
        move    a1,y:(r4+$1c)
        asr     #22,b,b                 ; -> frames, 24.24
        move    y:(r4+$1a),y0
        mpyuu   x1,y0,a                 ; u*r * 2^47 (u r/2, unsigned)
        asr     #23,a,a                 ; -> frames, 24.24
        sub     b,a
        move    y:(r4+$13),b          ; + the previous output's position
        asr     b                       ; (ring words -> frames; even, so b0 stays 0)
        move    y:(r4+$14),b0
        add     b,a
        sub     #<$7,a                ; first tap = floor(pos) - 2c - 1
        move    a0,b
        lsr     #19,b                   ; phase 0..31
        lsl     #3,b                    ; x 8 taps
        add     #>$a80,b
        asl     a       r5,n1           ; frames -> words; r5 (this pass's table) is
        and     #>$7e,a                 ; borrowed until zqbl
        move    a1,n2
        move    b1,r5
        lua     (r2)+n2,r1              ; (r2 is 128-aligned: m1 = $7f wraps r1 in the ring)
        move    y:(r4+$c),y1          ; the step it replaces
; ---- the mid's virtual ADC: 8 taps over L + R (the sum, halved below)
        clr     a       x:(r1)+,x0      y:(r5)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     y0,x0,a x:(r1)+,x0      y:(r5)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     y0,x0,a x:(r1)+,x0      y:(r5)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     y0,x0,a x:(r1)+,x0      y:(r5)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     y0,x0,a x:(r1)+,x0      y:(r5)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     y0,x0,a x:(r1)+,x0      y:(r5)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     y0,x0,a x:(r1)+,x0      y:(r5)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     y0,x0,a x:(r1)+,x0      y:(r5)+,y0
        mac     y0,x0,a x:(r1)+,x0
        mac     y0,x0,a
        asr     a                       ; (L + R) / 2
        move    a,x0                    ; limited
        move    x0,a
        and     #>$fff000,a             ; the new step, 12 bits
        move    a1,y:(r4+$c)
        sub     y1,a
        asr     a
        move    a,y1                    ; (new - old)/2
; ---- the step into the render: row floor(uR) of the transposed table holds
; the L taps' (T, D) pairs in order; the weight is T + frac(uR) D
        move    x1,a
        lsr     #19,a                   ; floor(uR), R = 16
        lsl     #2,a
        move    a1,x0
        lsl     #2,a
        add     x0,a                    ; x 2L = 20 words a row
        add     #>$e00,a
        move    a1,r5
        move    x1,a
        lsl     #4,a
        and     #>$7fffff,a
        move    a1,x0                   ; frac(uR), Q23
        move    y:(r5)+,a               ; T
        move    y:(r5)+,y0              ; D
        do      #$a,zqbl
        mac     y0,x0,a y:(r7),b        ; a = weight/2 = T + frac D; b = the ring
        move    a,x1    y:(r5)+,a       ; next T
        mac     y1,x1,b y:(r5)+,y0      ; b += step/2 x weight/2; next D
        move    b,y:(r7)+
zqbl:
        move    n1,r5
; ---- out: the mid = the current step + what the render still owes this output;
; ch6: through channel 6 (section 1: b (x + x[n-1]) + q s1[n-1]; section 2 at half
; scale, doubled: g/2 s1 - a1/2 s2[n-1] - a2/2 s2[n-2])
zqout:
        clr     b
        move    y:(r7),a
        asl     #2,a,a
        move    y:(r6)+,x0              ; HM
        add     x0,a    b,y:(r7)+       ; (the slot is spent)
        move    a,x0    y:(r6),y0       ; mid (limited); XP = x[n-1]
        move    #>$2e147b,x1
        mpy     x1,x0,a x0,y:(r6)+
        mac     x1,y0,a y:(r6),y0       ; Y1 = s1[n-1]
        maci    #$23d70a,y0,a
        move    a,x0    a,y:(r6)+       ; s1 (limited)
        mpyi    #$5618cd,x0,a
        move    y:(r6)+,y1              ; Z2 = s2[n-2]
        move    y:(r6)-,y0              ; Z1 = s2[n-1]
        maci    #$fe0f5d,y0,a
        maci    #$ebd7d6,y1,a
        asl     a       y0,y:(r6)+
        move    a,x0    a,y:(r6)+       ; s2 (limited)
        move    x0,n5                   ; (n5: free outside the tick)
; ---- the side, clean: (L - R)/2 at the OT's position less the offset, linear
; between its two frames. l:(r5) = (ring words, fraction): less (2 int, frac) of the
; offset, the words' LSB is the fraction's borrow, which the $7e mask drops
        move    l:(r5)+,a
        move    y:(r6)+,y1              ; OH
        move    y:(r6)+,y0              ; OL
        move    a1,y:(r6)+              ; this output becomes "previous"
        sub     y,a     a0,y:(r6)+
        move    a0,b
        move    y:(r6)+,y1              ; RB: the ring is 128-aligned, so OR adds it
        and     #>$7e,a
        or      y1,a    y:(r6)+,x1      ; $7fffff
        lsr     b       a1,r1           ; g = the fraction, Q23
        move    b1,y0
        move    x1,b
        sub     y0,b    x:(r1)+,a       ; 1 - g; L0
        move    x:(r1)+,x0      b,y1    ; R0
        sub     x0,a    x:(r1)+,b       ; L1
        asr     a       x:(r1)+,x0      ; (L0 - R0)/2; R1
        sub     x0,b    a,x1
        asr     b                       ; (L1 - R1)/2
        mpy     y1,x1,a b,x1
        mac     x1,y0,a y:(r6),b        ; the previous side sample
        move    a,x0                    ; the side (limited)
        add     x0,b    x0,y:(r6)+n6    ; (r6 back to TAU)
        asr     b                       ; the two-sample average: the channel filter's zero at Nyquist
        move    b,x0
        move    n5,a
        add     x0,a    n5,b
        sub     x0,b    a,x:(r3)+       ; L = mid + side
        move    b,x:(r3)+               ; R = mid - side
zqoe:
        move    r7,y:(r4+$19)
        move    n7,m7


zqdone:
        move    n4,m1
        move    #$0,r7                  ; the stock kernel's `do r7` skips
zqstk:
        move    x:(r5),n6               ; displaced from the hook site
        move    y:(r5)+,a
        rts

; ---------------------------------------------------------------------------
; zqboot (rev 17): the table copy at boot, outside every audio pass (the KYOTI
; load audit: on a core's first RPS9/RPSP pass it cost one frame ~5,000
; instructions on top of its audio). Hooked at the payload's one-time memory
; clear, before its frame loop exists: A P:0x46 / B P:0x47, `do b,LA` with
; a = 0, b = the count, r4/r5 its two pointers. This runs the clear's passes
; but the last; the stock body at the return address runs that one, so the
; memory the clear leaves is stock's (an extra pass would write one word past
; each run -- on payload A, Y:$38000, payload B's entry in the shared window).
; Then zqinit, with the registers it uses kept on the hardware stack. zqrp's
; tag check stays: it rebuilds Y if anything ever overwrites the tables. (Placed
; before zqinit: octabam's dsp_asm sizes a backward call differently per pass.)
zqboot:
        move    #>1,x0
        sub     x0,b
        do      b,zqbz
        move    a,y:(r4)+
        move    a,y:(r5)+
zqbz:
        add     x0,b                    ; the count, as the stock DO leaves it
        move    b1,ssh                  ; the registers zqinit uses, on the hardware
        move    r1,ssh                  ; stack (the boot path is shallow: jsr + five +
        move    r4,ssh                  ; bsr + one DO)
        move    n2,ssh
        move    n4,ssh
        bsr     zqinit
        move    ssh,n4
        move    ssh,n2
        move    ssh,r4
        move    ssh,r1
        move    ssh,b
        clr     a
        rts

; ---------------------------------------------------------------------------
; zqinit: copy the tables into Y (first use on a core, or a new build). The
; virtual-ADC tables arrive as their 16 stored half-rows; row 31-ph is row ph
; reversed, so one forward pass writes row ph going up and its mirror going
; down from the table's end (rev 12's copy). The render arrives as T[0..LR/2].
; Preserves r5 and r7 (hardware stack: one bsr and one DO below zqrp).
zqinit:
        move    r7,n2
        move    #>$fab2e0,r1            ; block 2: the RPSP half-rows; the RPS9 rows follow
        move    #>$a80,r4
        move    #>$b7f,r7
        do      #$80,zqi1
        move    p:(r1)+,x0
        move    x0,y:(r4)+
        move    x0,y:(r7)-
zqi1:
        move    #>$c00,r4              ; r1 is at XR9: it follows XSP
        move    #>$dff,r7
        do      #$100,zqi2
        move    p:(r1)+,x0
        move    x0,y:(r4)+
        move    x0,y:(r7)-
zqi2:
        move    #>$fab1e0,r1             ; block 1: the render's half-table
        move    #>$f40,r4               ; T[0..LR] into a scratch run first
        move    #>$fe0,r7
        move    #>$c00000,y0            ; -1/2
        do      #$51,zqi3             ; T[k] stored for k = 0..LR/2; T[LR-k] = -1/2 - T[k]
        move    p:(r1)+,x0
        move    x0,y:(r4)+
        move    y0,a
        sub     x0,a
        move    a1,y:(r7)-
zqi3:
; the render's table, transposed (rev 17): row j (one per segment) holds the L
; taps' (T[k], D[k] = T[k+1] - T[k]) pairs in tap order, tap m at segment
; k = (L-1-m)R + j, so a tick walks one row with (r5)+. One DO (the hardware
; stack's budget): every L pairs the next row starts one segment up.
        move    #>$e00,r1
        move    #>$fd0,r7              ; row 0, tap 0
        move    r7,r4
        move    #>$ffffef,n4              ; k+1 -> k-R (n1 holds zqrp's mode)
        move    #>$a,b
        do      #$a0,zqi4
        move    y:(r4)+,x0              ; T[k]
        move    y:(r4)+n4,a             ; T[k+1]
        sub     x0,a    x0,y:(r1)+
        move    a1,y:(r1)+
        sub     #<1,b
        bne     zqi5
        move    (r7)+
        move    r7,r4
        move    #>$a,b
zqi5:
        nop                             ; (the loop's last word: a branch target)
zqi4:
        move    #>$504a23,x0
        move    x0,y:>$a7f
        move    n2,r7
        rts
