#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Zac-Kyoti
"""
REPITCH_REPEAT98_KYOTI's octabam kernel (octabam-modules/repitch-repeat98-kyoti/
rpk_dsp.asm, generated by tools/repitch_dsp_octabam.py) against the reference
model, in both places octabam can put its table block:

  P    the block in P directly below the code (octabam: a stock reader of the
       curve bank is kept); the `p:(rN)` reads stay
  X    the block in the stock curve bank at X:0x4840 (octabam: no reader kept);
       every `p:(` becomes `x:(`, as octabam's build rewrites it

Same probe, schedule, signals and DSP-exact twin as tools/repitch_dsp_engine_check.py
(the standalone kernel's check), on both payloads' voice modules. Assembled by
tools/dsp_xasm.py: octabam's own dsp_asm builds the XY+ALU moves only once
sambanks/octabam#561's assembler fix lands.

    python3 tools/repitch_dsp_octabam_check.py
"""
import pathlib
import sys

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import dsp_xasm                           # noqa: E402
import repitch_dsp_engine_check as ec     # noqa: E402
import repitch_dsp_octabam as gen         # noqa: E402

ec.WORK = ROOT / "out/repitch_octabam_check"
CURVE_BANK = 0x4840
MARK = "$" + "fab1e0"


def build(tag, placement):
    """(cave words, cave org, entry) for one payload and placement; writes the
    probe's cave and X-data files."""
    src, _, words, _, _ = gen.generate()
    org = ec.dsrc.SPRING_P[tag]                   # SPRING's words, as the test remixes give them up
    if placement == "P":
        base, code_org = org, org + len(words)
        asm = src.replace(MARK, f"${base:x}")
        code, syms = dsp_xasm.assemble(asm, code_org)
        cave = list(words) + code
        xdata = {}
    else:
        base, code_org = CURVE_BANK, org
        asm = "\n".join(l.split(";")[0].replace("p:(", "x:(") + (";" + l.split(";", 1)[1] if ";" in l else "")
                        for l in src.replace(MARK, f"${base:x}").splitlines()) + "\n"
        code, syms = dsp_xasm.assemble(asm, code_org)
        cave = code
        xdata = {base + i: w for i, w in enumerate(words)}
    assert syms["zqrp"] == code_org, "zqrp must start the code"
    (ec.WORK / f"cave_{tag}.bin").write_bytes(b"".join(w.to_bytes(3, "little") for w in cave))
    (ec.WORK / f"xdata_{tag}.txt").write_text("".join(f"{a:x} {w:x}\n" for a, w in sorted(xdata.items())))
    return cave, org, code_org, len(code)


def main():
    ec.WORK.mkdir(parents=True, exist_ok=True)
    ec.build_probe()
    ec.SCHED = ec.schedule(4000)
    (ec.WORK / "sched.txt").write_text("".join(f"{k:x} {f:x} {lv:x}\n" for k, f, lv in ec.SCHED))
    img = ec.chk.IMG.read_bytes()
    results, cost = [], {}
    for placement in ("P", "X"):
        for tag, va, ln, base, hook, stop in ec.chk.PAYLOADS:
            mod, _ = ec.chk.voice_module(img, va, ln, base)
            (ec.WORK / f"voice_{tag}.bin").write_bytes(mod)
            cave, org, entry, ncode = build(tag, placement)
            c = ec.dsrc.constants(tag)
            b0, b1 = ec.sc3.bsr_long(hook, entry)
            print(f"{placement} payload {tag}: code {ncode} words @P:{entry:05x}"
                  f"{f', tables P:{org:05x}' if placement == 'P' else f', tables X:{CURVE_BANK:05x}'}")
            n_frames = int(1.0 * ec.SR)
            for sname, (L, R) in ec.signals(n_frames).items():
                src = np.empty(2 * n_frames, dtype=np.int64)
                src[0::2], src[1::2] = ec.as24(L), ec.as24(R)
                inp = ec.WORK / f"{sname}.raw"
                inp.write_bytes(src.astype("<i4").tobytes())
                for ratio in (1.0, 0.75, 1.5, 0.5, 1.99):
                    inc = int(round(ratio * (1 << 24)))
                    rint, rfrac = inc >> 24, inc & 0xFFFFFF
                    for mode, mname in ((1, "RPS9"), (2, "RPSP")):
                        o = ec.WORK / f"{placement}{tag}_{sname}_{ratio}_{mname}.raw"
                        cnt = ec.WORK / f"{placement}{tag}_{sname}_{ratio}_{mname}.cnt"
                        dsp = ec.run_probe(tag, base, hook, stop, org, b0, b1, mode, rint, rfrac, inp, o, cnt)
                        twin = ec.model_run(mode, src, rint, rfrac, exact=ec.exact_for(mode, c),
                                            sched=ec.SCHED).reshape(-1)
                        k = min(len(dsp), len(twin))
                        same = bool(np.array_equal(dsp[:k], twin[:k]))
                        per = float(np.median([int(v) for v in cnt.read_text().split()][1:])) / 16.0
                        cost.setdefault((placement, mname), []).append(per)
                        results.append(same)
                        if not same:
                            print(f"  FAIL {sname} {ratio} {mname}: "
                                  f"{100 * float(np.mean(dsp[:k] != twin[:k])):.2f}% of samples differ")
            L, R = ec.signals(n_frames)["drum"]
            src = np.empty(2 * n_frames, dtype=np.int64)
            src[0::2], src[1::2] = ec.as24(L), ec.as24(R)
            for label, ok, detail in ec.switch_check(tag, base, hook, stop, org, b0, b1, c, src):
                results.append(ok)
                if not ok:
                    print(f"  FAIL mode switch {label}: {detail}")
    print(f"\n{sum(results)}/{len(results)} PASS (bit-exact with the DSP-exact twin, and the mode switch)")
    for (p, mname), v in sorted(cost.items()):
        print(f"  {p} {mname}: median {np.median(v):.1f} instr/sample, range {min(v):.1f}-{max(v):.1f}")
    sys.exit(0 if all(results) else 1)


if __name__ == "__main__":
    main()
